### ISSUE TITLE
changelog history encountering 'null' type 'toString' throws AttributeError

### ISSUE THREAD

**Issue by andrew-hamlin-sp** [andrew-hamlin-sp/jira_reporting_scripts#1]
Found on IIQETN-5786

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/__main__.py", line 207, in <module>
    main(args=sys.argv[1:])
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/__main__.py", line 199, in main
    unicode_csv_writer.write(f, command, encoding)
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/unicode_csv_writer.py", line 26, in write
    for row in command.execute():
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/command.py", line 133, in <genexpr>
    generate_rows = ({k:v for k,v in flatten_rows(x)}
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/command.py", line 149, in pre_process
    for x in generate_data:
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/jira.py", line 138, in all_issues
    yield _as_data(issue, reverse_sprints=reverse_sprints)
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/jira.py", line 79, in _as_data
    for h in histories for item in h['items'] if 'fieldId' in item])
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/jira.py", line 79, in <listcomp>
    for h in histories for item in h['items'] if 'fieldId' in item])
  File "/Users/andrew.hamlin/tools/jira_reporting_scripts/.py3/qjira/dataprocessor.py", line 17, in create_history
    normalized_string = hst['toString'].replace(' ', '')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by andrew-hamlin-sp** [comment]
Need to handle moving to a null status
{
                                "field": "status",
                                "fieldtype": "jira",
                                "fieldId": "status",
                                "from": null,
                                "fromString": null,
                                "to": "1",
                                "toString": null
                            }

**Comment by andrew-hamlin-sp** [comment]
Fixed in commit 8987624
